### PR TITLE
Ability to use MySQL database

### PR DESCRIPTION
**Pull request by maver1ck**
Solving
https://github.com/puckel/docker-airflow/issues/200

### CODE REVIEW

**Comment by jensenity** [comment]
This will be good as I'm trying to use RDS instead of using postgres db on the Ubuntu machine.

**Comment by maver1ck** [comment]
ping @danrubenstein

**Comment by maver1ck** [comment]
ping @danrubenstein one more time

**Comment by maver1ck** [comment]
ping @puckel

**Comment by ebartels** [comment]
@puckel What is blocking this from being merged?  I'm a MySQL airflow user and would benefit from being able to use this.

**Comment by danrubenstein** [comment]
Hi @maver1ck,

Apologies that I missed this -- I'm going to defer to the maintainers on whether or not to accept this.

Thanks

**Comment by zhongjiajie** [comment]
More easy to do like https://github.com/puckel/docker-airflow/pull/253, just pass `AIRFLOW__CORE__SQL_ALCHEMY_CONN` and `AIRFLOW__CELERY__RESULT_BACKEND`

**Comment by brunowego** [comment]
@zhongjiajie because of this:

https://github.com/puckel/docker-airflow/blob/42902d01c61297b0c7559770a8d06f93e5fc7dc0/script/entrypoint.sh#L59-L63

Did you have an idea to bypass this without rewrite this file?

**Comment by dene14** [comment]
Why not package all supported/available drivers and let people chose which one they want to use?
Then general connection string template will look like this:
```
${DB_CONN_SCHEMA}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?${DB_OPTIONS}
```

**Pull request closed without merging**
