### PR TITLE
Bump airflow to 1.10.3

### PR DESCRIPTION
**Pull request by rgangopadhya**
Changelog: https://github.com/apache/airflow/blob/1.10.3/CHANGELOG.txt

### CODE REVIEW

**Comment by mdcurran** [comment]
There have been some [config changes](https://github.com/apache/airflow/blob/1.10.3/UPDATING.md) in 1.10.3.

Things like:
* SLUGIFY_USES_TEXT_UNIDECODE or AIRFLOW_GPL_UNIDECODE no longer required
* Removal of airflow_home config setting

To keep this repo closely aligned with the main Airflow repo, it would be worth removing the relevant options here as well. Only thing I'm unsure about is if there might be any backwards compatibility issues?

**Comment by rgangopadhya** [comment]
Good catch, definitely worth taking a look at. I'm OOO the next few days so if anyone else wants to take this on before I return, please feel free.

**Comment by dostiharise** [comment]
> There have been some [config changes](https://github.com/apache/airflow/blob/1.10.3/UPDATING.md) in 1.10.3.
> 
> Things like:
> 
> * SLUGIFY_USES_TEXT_UNIDECODE or AIRFLOW_GPL_UNIDECODE no longer required
> * Removal of airflow_home config setting
> 
> To keep this repo closely aligned with the main Airflow repo, it would be worth removing the relevant options here as well. Only thing I'm unsure about is if there might be any backwards compatibility issues?

Dropping the `airflow_home` from the config setting in file `config/airflow.cfg` forces Airflow to initialise at`/usr/local/airflow/airflow`. 

this results in 2 files :

1. `/usr/local/airflow/airflow.cfg` from Docker image
2. `/usr/local/airflow/airflow/airflow.cfg` when airflow starts?

**Comment by dostiharise** [comment]
> > There have been some [config changes](https://github.com/apache/airflow/blob/1.10.3/UPDATING.md) in 1.10.3.
> > Things like:
> > 
> > * SLUGIFY_USES_TEXT_UNIDECODE or AIRFLOW_GPL_UNIDECODE no longer required
> > * Removal of airflow_home config setting
> > 
> > To keep this repo closely aligned with the main Airflow repo, it would be worth removing the relevant options here as well. Only thing I'm unsure about is if there might be any backwards compatibility issues?
> 
> Dropping the `airflow_home` from the config setting in file `config/airflow.cfg` forces Airflow to initialise at`/usr/local/airflow/airflow`.
> 
> this results in 2 files :
> 
> 1. `/usr/local/airflow/airflow.cfg` from Docker image
> 2. `/usr/local/airflow/airflow/airflow.cfg` when airflow starts?

PR #355 attempts to solve this problem, however might need a minor fix to be made.

**Pull request closed without merging**
