### PR TITLE
Bump to 1.10.3

### PR DESCRIPTION
**Pull request by naseemkullah**
https://github.com/apache/airflow/blob/master/CHANGELOG.txt

### CODE REVIEW

**Comment by rjrbt** [comment]
among other things, this adds support for ECS's networkMode of `awsvpc`
in `airflow/contrib/operators/ecs_operator.py` and allows for the `network_configuration` arg to be bassed in. +1 on bumping this.

**Comment by legal90** [comment]
This PR duplicates #355, #356

**Comment by naseemkullah** [comment]
> This PR duplicates #355, #356

Not quite, as they have additional changes whereas this one simply bumps the version. But you were probably too busy giving a thumbs down to notice that. 🥇

**Comment by naseemkullah** [comment]
This one only bumps the version whereas the the other two have additional changes. If either of those two get merged I will close this one. No need for thumbs down @legal90 and @stjindehaes please control your negativity

**Comment by naseemkullah** [comment]
Does not seem like this will be merged. Closing

**Pull request closed without merging**
