### PR TITLE
Fix celery result_backend config variable

### PR DESCRIPTION
**Pull request by diraol**
The variable was prepended with "celery_", which is wrong. It is already under
the "celery" group.

### CODE REVIEW

**Comment by ashb** [comment]
This is incorrect for the _released_ version of Airflow (1.9.0) the variables still need to prefixed with `celery_` https://github.com/apache/incubator-airflow/blob/1.9.0/airflow/config_templates/default_airflow.cfg#L257-L283

(The extra prefix has  been released in airflow's master branch)

**Comment by diraol** [comment]
@ashb is it really wrong?

https://github.com/apache/incubator-airflow/blob/a1d5551777739a166da8c770262f90ed47802857/UPDATING.md#celery-config

**Comment by ashb** [comment]
You are looking at the development version of Airflow.

The same file in the 1.9.0 tag doesn't include that section https://betterexplained.com/articles/techniques-for-adding-the-numbers-1-to-100/.

This change _will_ be right for Airflow 1.10, but won't work with any released version of Airflow.

**Comment by diraol** [comment]
Oh! Got, my fault! =)

Thanks for letting me know that. =)

**Pull request merged**
