### PR TITLE
Add packages which allow Airflow mysql hook

### PR DESCRIPTION
**Pull request by arihantsurana**
Currently, the Airflow mysql_hook import fails because the related MySqlDb packages are not installed, which is dependent on mysql_config being present from the mysql installation available on the machine.
This pull request adds necessary packages to allow airflow hooks for mysql to function.

### CODE REVIEW

**Comment by etrevisani** [comment]
Hi @arihantsurana. Is it necessary to install mysql-server in order to import and use MySQLHook? I'm asking because this package by itself adds around 200 MB to the layer.

**Comment by etrevisani** [comment]
Hi @arihantsurana. Is it necessary to install mysql-server in order to import and use MySQLHook? I'm asking because this package itself adds around 200 MB to the layer.

**Comment by arihantsurana** [comment]
I tried using the MySql hook with a mysql client, and could not get it to work with the airflow 1.9
however, I have got it working with `pip install mysqlclient` and `pip install apache-airflow[mysql]` using Airflow 1.10

Will add a PR soon, to reflect that.

**Comment by arihantsurana** [comment]
@etrevisani adding a fix - https://github.com/puckel/docker-airflow/pull/263

**Pull request merged**
