### PR TITLE
add kubernetes dependency when installing airflow

### PR DESCRIPTION
**Pull request by javefang**

### CODE REVIEW

**Comment by svweber** [comment]
@javefang I've added the plugin to my custom image as well. 

Though, I'm not able to get the Kubernetes Pod Operator running. I receive the following error message: 


[2018-12-26 16:46:08,926] {{models.py:1760}} ERROR - [Errno 13] Permission denied: '/var/run/secrets/kubernetes.io/serviceaccount/token'

I assume it's because the image is running as airflow non-root user. 

I'm curious how you managed to get it running?

**Comment by javefang** [comment]
Hi @svweber , I ends up building my own docker-airflow image with puckel's dockerfile and the `--build-arg` flags to specify additional plugins I need (kubernetes). This means airflow runs as user "airflow" as specified in the Dockerfile and I don't seem to have the same problem as you did.

Are you using the [airflow helm chart](https://github.com/helm/charts/tree/master/stable/airflow)? If not then you will have to configure RBAC in Kubernetes to create a new service account and relevant Role and RoleBinding to grant the service account sufficient permissions to create new Pods in your Kubernetes cluster, as the default service account has no such permission by default.

**Comment by svweber** [comment]
Hi @javefang , yes. I'm using the helm chart with the following options:

rbac:
  create: true

serviceAccount:
  create: true
  name: scheduler


In the KubernetesPodOperator, I've set the following: 

name="etl-task",
task_id="task",
image="my-private-repo",
namespace='default',
in_cluster=True,
startup_timeout_seconds=120,
get_logs=True,
image_pull_policy='Always',
image_pull_secrets="default-secret",
service_account_name="scheduler",
is_delete_operator_pod=True,

**Comment by javefang** [comment]
It's hard to debug this without seeing your whole Kubernetes setup. Another guess, I can see in your KubernetesPodOperator config that you are starting pods in namespace "default". Do you have airflow deployed to namespace "default" as well? (which should create a service account called "scheduler" under the same namespace.

**Comment by javefang** [comment]
I'm closing this as there doesn't seem to pick up any interest and I can build my own image to install the missing dependencies. It's probably better to keep this image lean.

**Comment by AXington** [comment]
really wish this would have been merged :(

**Pull request closed without merging**
